# Exercise for Classification

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv ("./data_files/credit-g.csv", na_values="?")
df

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,'<0',6,'critical/other existing credit',radio/tv,1169,'no known savings','>=7',4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,'0<=X<200',48,'existing paid',radio/tv,5951,'<100','1<=X<4',2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,'<100','4<=X<7',2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,'<0',42,'existing paid',furniture/equipment,7882,'<100','4<=X<7',2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,'<0',24,'delayed previously','new car',4870,'<100','1<=X<4',3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,'no checking',12,'existing paid',furniture/equipment,1736,'<100','4<=X<7',3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,'<0',30,'existing paid','used car',3857,'<100','1<=X<4',4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,'<100','>=7',4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,'<0',45,'existing paid',radio/tv,1845,'<100','1<=X<4',4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,'0<=X<200',45,'critical/other existing credit','used car',4576,'100<=X<500',unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

## Goal:
We will learn and compare predictors for the class attribute (will a person get a credit or not). We will do this step-by-step

## Data exploration:
How many features and instances does this dataset have? What is the distribution of the target class?

In [3]:
# Number of instances
len (df)

1000

In [4]:
#Number of attributes:
len (df.columns)

21

In [5]:
df["class"].value_counts(normalize=True)

good    0.7
bad     0.3
Name: class, dtype: float64

## Create a numpy array for the target class
Remember that the array should contain only 1 and 0

In [6]:
from sklearn import preprocessing
y = preprocessing.LabelEncoder().fit_transform(df["class"].values)
y

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

## Create the numpy arrays of feature values
Split categorical variables into binary ones!

In [7]:
df_features = df.drop(["class"], axis=1)
df_features = pd.get_dummies(df_features)
df_features

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents,checking_status_'0<=X<200',checking_status_'<0',checking_status_'>=200',...,housing_own,housing_rent,job_'high qualif/self emp/mgmt',job_'unemp/unskilled non res',job_'unskilled resident',job_skilled,own_telephone_none,own_telephone_yes,foreign_worker_no,foreign_worker_yes
0,6,1169,4,4,67,2,1,0,1,0,...,1,0,0,0,0,1,0,1,0,1
1,48,5951,2,2,22,1,1,1,0,0,...,1,0,0,0,0,1,1,0,0,1
2,12,2096,2,3,49,1,2,0,0,0,...,1,0,0,0,1,0,1,0,0,1
3,42,7882,2,4,45,1,2,0,1,0,...,0,0,0,0,0,1,1,0,0,1
4,24,4870,3,4,53,2,2,0,1,0,...,0,0,0,0,0,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,12,1736,3,4,31,1,1,0,0,0,...,1,0,0,0,1,0,1,0,0,1
996,30,3857,4,4,40,1,1,0,1,0,...,1,0,1,0,0,0,0,1,0,1
997,12,804,4,4,38,1,1,0,0,0,...,1,0,0,0,0,1,1,0,0,1
998,45,1845,4,4,23,1,1,0,1,0,...,0,0,0,0,0,1,0,1,0,1
999,45,4576,3,4,27,1,1,1,0,0,...,1,0,0,0,0,1,1,0,0,1

In [8]:
    X = df_features.values

## Split the data randomly into 50% training and 50% test data

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

## Learn a Random Forest classifier on the training data

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
clf = RandomForestClassifier()
clf.fit (X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [12]:
sum(clf.predict(X_train) == y_train) / len(y_train)

1.0

## Predict the class labels for the test dataset
Predict either absolute (1 or 0) or as probabilities

In [13]:
clf.predict (X_test)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
clf.predict_proba (X_test)

array([[0.44, 0.56],
       [0.28, 0.72],
       [0.41, 0.59],
       [0.13, 0.87],
       [0.42, 0.58],
       [0.28, 0.72],
       [0.07, 0.93],
       [0.56, 0.44],
       [0.37, 0.63],
       [0.08, 0.92],
       [0.07, 0.93],
       [0.63, 0.37],
       [0.37, 0.63],
       [0.22, 0.78],
       [0.13, 0.87],
       [0.13, 0.87],
       [0.34, 0.66],
       [0.28, 0.72],
       [0.26, 0.74],
       [0.33, 0.67],
       [0.48, 0.52],
       [0.22, 0.78],
       [0.28, 0.72],
       [0.47, 0.53],
       [0.05, 0.95],
       [0.36, 0.64],
       [0.04, 0.96],
       [0.22, 0.78],
       [0.48, 0.52],
       [0.53, 0.47],
       [0.63, 0.37],
       [0.12, 0.88],
       [0.61, 0.39],
       [0.39, 0.61],
       [0.55, 0.45],
       [0.35, 0.65],
       [0.44, 0.56],
       [0.56, 0.44],
       [0.21, 0.79],
       [0.11, 0.89],
       [0.02, 0.98],
       [0.36, 0.64],
       [0.14, 0.86],
       [0.24, 0.76],
       [0.64, 0.36],
       [0.37, 0.63],
       [0.35, 0.65],
       [0.09, 0.91],
       [0.18, 0.82],
       [0.61, 0.39],
       [0.19, 0.81],
       [0.47, 0.53],
       [0.07, 0.93],
       [0.62, 0.38],
       [0.38, 0.62],
       [0.6 , 0.4 ],
       [0.18, 0.82],
       [0.47, 0.53],
       [0.16, 0.84],
       [0.39, 0.61],
       [0.44, 0.56],
       [0.03, 0.97],
       [0.47, 0.53],
       [0.17, 0.83],
       [0.02, 0.98],
       [0.22, 0.78],
       [0.1 , 0.9 ],
       [0.43, 0.57],
       [0.56, 0.44],
       [0.47, 0.53],
       [0.1 , 0.9 ],
       [0.17, 0.83],
       [0.08, 0.92],
       [0.55, 0.45],
       [0.34, 0.66],
       [0.15, 0.85],
       [0.42, 0.58],
       [0.22, 0.78],
       [0.22, 0.78],
       [0.47, 0.53],
       [0.36, 0.64],
       [0.49, 0.51],
       [0.13, 0.87],
       [0.22, 0.78],
       [0.54, 0.46],
       [0.1 , 0.9 ],
       [0.05, 0.95],
       [0.36, 0.64],
       [0.32, 0.68],
       [0.15, 0.85],
       [0.35, 0.65],
       [0.05, 0.95],
       [0.22, 0.78],
       [0.02, 0.98],
       [0.23, 0.77],
       [0.22, 0.78],
       [0.19, 0.81],
       [0.04, 0.96],
       [0.2 , 0.8 ],
       [0.31, 0.69],
       [0.45, 0.55],
       [0.31, 0.69],
       [0.46, 0.54],
       [0.27, 0.73],
       [0.17, 0.83],
       [0.41, 0.59],
       [0.56, 0.44],
       [0.25, 0.75],
       [0.41, 0.59],
       [0.24, 0.76],
       [0.22, 0.78],
       [0.35, 0.65],
       [0.17, 0.83],
       [0.43, 0.57],
       [0.48, 0.52],
       [0.13, 0.87],
       [0.46, 0.54],
       [0.61, 0.39],
       [0.57, 0.43],
       [0.11, 0.89],
       [0.43, 0.57],
       [0.11, 0.89],
       [0.59, 0.41],
       [0.18, 0.82],
       [0.04, 0.96],
       [0.02, 0.98],
       [0.4 , 0.6 ],
       [0.54, 0.46],
       [0.16, 0.84],
       [0.21, 0.79],
       [0.43, 0.57],
       [0.11, 0.89],
       [0.14, 0.86],
       [0.07, 0.93],
       [0.3 , 0.7 ],
       [0.09, 0.91],
       [0.29, 0.71],
       [0.31, 0.69],
       [0.05, 0.95],
       [0.34, 0.66],
       [0.24, 0.76],
       [0.09, 0.91],
       [0.16, 0.84],
       [0.27, 0.73],
       [0.09, 0.91],
       [0.06, 0.94],
       [0.22, 0.78],
       [0.35, 0.65],
       [0.33, 0.67],
       [0.19, 0.81],
       [0.15, 0.85],
       [0.59, 0.41],
       [0.65, 0.35],
       [0.1 , 0.9 ],
       [0.27, 0.73],
       [0.29, 0.71],
       [0.14, 0.86],
       [0.38, 0.62],
       [0.18, 0.82],
       [0.3 , 0.7 ],
       [0.67, 0.33],
       [0.37, 0.63],
       [0.2 , 0.8 ],
       [0.29, 0.71],
       [0.45, 0.55],
       [0.5 , 0.5 ],
       [0.44, 0.56],
       [0.48, 0.52],
       [0.39, 0.61],
       [0.14, 0.86],
       [0.31, 0.69],
       [0.05, 0.95],
       [0.47, 0.53],
       [0.5 , 0.5 ],
       [0.22, 0.78],
       [0.42, 0.58],
       [0.38, 0.62],
       [0.48, 0.52],
       [0.13, 0.87],
       [0.3 , 0.7 ],
       [0.49, 0.51],
       [0.34, 0.66],
       [0.54, 0.46],
       [0.78, 0.22],
       [0.39, 0.61],
       [0.54, 0.46],
       [0.33, 0.67],
       [0.46, 0.54],
       [0.33, 0.67],
       [0.36, 0.64],
       [0.33, 0.67],
       [0.25, 0.75],
       [0.38, 0.62],
       [0.21, 0.79],
       [0.49, 0.51],
       [0.33, 0.67],
       [0.42, 0.58],
       [0.32, 0.68],
       [0.49, 0.51],
       [0.36, 0.64],
       [0.41, 0.59],
       [0.45, 0.55],
       [0.26, 0.74],
       [0.51, 0.49],
       [0.29, 0.71],
       [0.46, 0.54],
       [0.07, 0.93],
       [0.37, 0.63],
       [0.21, 0.79],
       [0.7 , 0.3 ],
       [0.17, 0.83],
       [0.28, 0.72],
       [0.18, 0.82],
       [0.13, 0.87],
       [0.59, 0.41],
       [0.17, 0.83],
       [0.44, 0.56],
       [0.55, 0.45],
       [0.43, 0.57],
       [0.3 , 0.7 ],
       [0.58, 0.42],
       [0.57, 0.43],
       [0.33, 0.67],
       [0.19, 0.81],
       [0.63, 0.37],
       [0.23, 0.77],
       [0.63, 0.37],
       [0.2 , 0.8 ],
       [0.3 , 0.7 ],
       [0.34, 0.66],
       [0.28, 0.72],
       [0.21, 0.79],
       [0.66, 0.34],
       [0.07, 0.93],
       [0.7 , 0.3 ],
       [0.05, 0.95],
       [0.56, 0.44],
       [0.4 , 0.6 ],
       [0.09, 0.91],
       [0.28, 0.72],
       [0.62, 0.38],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.15, 0.85],
       [0.13, 0.87],
       [0.35, 0.65],
       [0.62, 0.38],
       [0.11, 0.89],
       [0.38, 0.62],
       [0.12, 0.88],
       [0.06, 0.94],
       [0.19, 0.81],
       [0.17, 0.83],
       [0.21, 0.79],
       [0.1 , 0.9 ],
       [0.34, 0.66],
       [0.51, 0.49],
       [0.07, 0.93],
       [0.29, 0.71],
       [0.5 , 0.5 ],
       [0.44, 0.56],
       [0.46, 0.54],
       [0.05, 0.95],
       [0.61, 0.39],
       [0.53, 0.47],
       [0.35, 0.65],
       [0.43, 0.57],
       [0.36, 0.64],
       [0.2 , 0.8 ],
       [0.04, 0.96],
       [0.2 , 0.8 ],
       [0.14, 0.86],
       [0.23, 0.77],
       [0.1 , 0.9 ],
       [0.14, 0.86],
       [0.11, 0.89],
       [0.22, 0.78],
       [0.34, 0.66],
       [0.26, 0.74],
       [0.44, 0.56],
       [0.44, 0.56],
       [0.52, 0.48],
       [0.28, 0.72],
       [0.22, 0.78],
       [0.24, 0.76],
       [0.07, 0.93],
       [0.25, 0.75],
       [0.11, 0.89],
       [0.4 , 0.6 ],
       [0.64, 0.36],
       [0.35, 0.65],
       [0.22, 0.78],
       [0.68, 0.32],
       [0.21, 0.79],
       [0.08, 0.92],
       [0.3 , 0.7 ],
       [0.22, 0.78],
       [0.46, 0.54],
       [0.34, 0.66],
       [0.09, 0.91],
       [0.42, 0.58],
       [0.14, 0.86],
       [0.05, 0.95],
       [0.55, 0.45],
       [0.12, 0.88],
       [0.47, 0.53],
       [0.06, 0.94],
       [0.25, 0.75],
       [0.27, 0.73],
       [0.07, 0.93],
       [0.54, 0.46],
       [0.15, 0.85],
       [0.19, 0.81],
       [0.29, 0.71],
       [0.04, 0.96],
       [0.11, 0.89],
       [0.23, 0.77],
       [0.21, 0.79],
       [0.08, 0.92],
       [0.52, 0.48],
       [0.33, 0.67],
       [0.28, 0.72],
       [0.4 , 0.6 ],
       [0.18, 0.82],
       [0.27, 0.73],
       [0.3 , 0.7 ],
       [0.53, 0.47],
       [0.08, 0.92],
       [0.12, 0.88],
       [0.29, 0.71],
       [0.3 , 0.7 ],
       [0.41, 0.59],
       [0.28, 0.72],
       [0.35, 0.65],
       [0.1 , 0.9 ],
       [0.17, 0.83],
       [0.25, 0.75],
       [0.21, 0.79],
       [0.09, 0.91],
       [0.38, 0.62],
       [0.35, 0.65],
       [0.49, 0.51],
       [0.12, 0.88],
       [0.64, 0.36],
       [0.22, 0.78],
       [0.61, 0.39],
       [0.49, 0.51],
       [0.5 , 0.5 ],
       [0.35, 0.65],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.31, 0.69],
       [0.2 , 0.8 ],
       [0.28, 0.72],
       [0.33, 0.67],
       [0.42, 0.58],
       [0.36, 0.64],
       [0.14, 0.86],
       [0.05, 0.95],
       [0.46, 0.54],
       [0.15, 0.85],
       [0.24, 0.76],
       [0.53, 0.47],
       [0.34, 0.66],
       [0.21, 0.79],
       [0.24, 0.76],
       [0.42, 0.58],
       [0.21, 0.79],
       [0.08, 0.92],
       [0.1 , 0.9 ],
       [0.5 , 0.5 ],
       [0.02, 0.98],
       [0.36, 0.64],
       [0.24, 0.76],
       [0.24, 0.76],
       [0.38, 0.62],
       [0.4 , 0.6 ],
       [0.1 , 0.9 ],
       [0.13, 0.87],
       [0.74, 0.26],
       [0.51, 0.49],
       [0.36, 0.64],
       [0.23, 0.77],
       [0.29, 0.71],
       [0.13, 0.87],
       [0.42, 0.58],
       [0.43, 0.57],
       [0.32, 0.68],
       [0.39, 0.61],
       [0.6 , 0.4 ],
       [0.26, 0.74],
       [0.2 , 0.8 ],
       [0.66, 0.34],
       [0.26, 0.74],
       [0.29, 0.71],
       [0.45, 0.55],
       [0.11, 0.89],
       [0.13, 0.87],
       [0.3 , 0.7 ],
       [0.24, 0.76],
       [0.41, 0.59],
       [0.29, 0.71],
       [0.19, 0.81],
       [0.26, 0.74],
       [0.05, 0.95],
       [0.15, 0.85],
       [0.25, 0.75],
       [0.03, 0.97],
       [0.56, 0.44],
       [0.02, 0.98],
       [0.33, 0.67],
       [0.35, 0.65],
       [0.43, 0.57],
       [0.23, 0.77],
       [0.81, 0.19],
       [0.23, 0.77],
       [0.24, 0.76],
       [0.34, 0.66],
       [0.39, 0.61],
       [0.33, 0.67],
       [0.18, 0.82],
       [0.39, 0.61],
       [0.36, 0.64],
       [0.02, 0.98],
       [0.34, 0.66],
       [0.39, 0.61],
       [0.37, 0.63],
       [0.07, 0.93],
       [0.2 , 0.8 ],
       [0.07, 0.93],
       [0.07, 0.93],
       [0.24, 0.76],
       [0.32, 0.68],
       [0.63, 0.37],
       [0.17, 0.83],
       [0.63, 0.37],
       [0.57, 0.43],
       [0.27, 0.73],
       [0.56, 0.44],
       [0.68, 0.32],
       [0.11, 0.89],
       [0.54, 0.46],
       [0.41, 0.59],
       [0.04, 0.96],
       [0.24, 0.76],
       [0.18, 0.82],
       [0.06, 0.94],
       [0.14, 0.86],
       [0.05, 0.95],
       [0.01, 0.99],
       [0.06, 0.94],
       [0.12, 0.88],
       [0.53, 0.47],
       [0.09, 0.91],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [0.42, 0.58],
       [0.27, 0.73],
       [0.5 , 0.5 ],
       [0.24, 0.76],
       [0.26, 0.74],
       [0.29, 0.71],
       [0.08, 0.92],
       [0.46, 0.54],
       [0.3 , 0.7 ],
       [0.23, 0.77],
       [0.1 , 0.9 ],
       [0.36, 0.64],
       [0.29, 0.71],
       [0.31, 0.69],
       [0.12, 0.88],
       [0.21, 0.79],
       [0.09, 0.91],
       [0.08, 0.92],
       [0.66, 0.34],
       [0.36, 0.64],
       [0.52, 0.48],
       [0.14, 0.86],
       [0.35, 0.65],
       [0.34, 0.66],
       [0.14, 0.86],
       [0.2 , 0.8 ],
       [0.36, 0.64],
       [0.53, 0.47],
       [0.26, 0.74],
       [0.3 , 0.7 ],
       [0.05, 0.95],
       [0.48, 0.52],
       [0.07, 0.93],
       [0.36, 0.64],
       [0.78, 0.22],
       [0.39, 0.61],
       [0.14, 0.86],
       [0.23, 0.77],
       [0.11, 0.89],
       [0.31, 0.69],
       [0.45, 0.55],
       [0.14, 0.86],
       [0.31, 0.69],
       [0.47, 0.53]])

## Which features to influence the  classifier most?

In [15]:
fi = clf.feature_importances_
feature_importances_df = pd.DataFrame ({"Feature" : df_features.columns, "importance": fi})
feature_importances_df.sort_values("importance", ascending=False).head(5)

                          Feature  importance
1                   credit_amount    0.104235
4                             age    0.074082
0                        duration    0.068460
10  checking_status_'no checking'    0.053683
2          installment_commitment    0.034783

## What is the accuracy of this classifier on the _Training Data_?

In [16]:
(clf.predict(X_train) == y_train).sum() / len(y_train)

1.0

## What is the accuracy of this classifier on the _Test Data_?

In [17]:
(clf.predict(X_test) == y_test).sum() / len(y_test)

0.768

## What is the mean 10-fold cross-validated accuracy of this classifier?

In [18]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, X, y, cv=10, scoring="accuracy").mean()

0.7639999999999999

## How long did the cross-validation take?

In [19]:
%time cross_val_score(clf, X, y, cv=10, scoring="accuracy")

CPU times: user 2.54 s, sys: 30.2 ms, total: 2.57 s
Wall time: 2.69 s

array([0.79, 0.71, 0.75, 0.76, 0.77, 0.79, 0.71, 0.82, 0.75, 0.79])

## Compare this with a variety of other classifiers of your choice

In [20]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB

In [21]:
clf_names = ["k-Nearest Neighbors", 
             "Decision Tree", 
             "Random Forest", 
             "Neural Net", 
             "Naive Bayes",
             "AdaBoost"]
clfs = [KNeighborsClassifier(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    MLPClassifier(),
    GaussianNB(),
    AdaBoostClassifier()]

In [22]:
for name, clf in zip(clf_names, clfs):
    acc = cross_val_score(clf, X, y, cv=10, scoring="accuracy").mean()
    print ("Accuracy of %s according to cross-validation: %s" % (name, acc))

Accuracy of k-Nearest Neighbors according to cross-validation: 0.6540000000000001
Accuracy of Decision Tree according to cross-validation: 0.683
Accuracy of Random Forest according to cross-validation: 0.767
Accuracy of Neural Net according to cross-validation: 0.6910000000000001
Accuracy of Naive Bayes according to cross-validation: 0.714
Accuracy of AdaBoost according to cross-validation: 0.748

# Congressional Data:
This data set includes votes for each of the U.S. House of Representatives Congressmen on the 16 key votes identified by the CQA. The CQA lists nine different types of votes: voted for, paired for, and announced for (these three simplified to yea), voted against, paired against, and announced against (these three simplified to nay), voted present, voted present to avoid conflict of interest, and did not vote or otherwise make a position known (these three simplified to an unknown disposition).

Source: https://archive.ics.uci.edu/ml/datasets/congressional+voting+records

Task: Build a classifier that can predict the party of a congress member based on his decision. use the last 50 instances of the dataset as a test set

In [23]:
df = pd.read_csv ("./data_files/vote.csv", na_values="?")
df

,party,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
432,republican,n,NaN,n,y,y,y,n,n,n,n,y,y,y,y,n,y
433,republican,n,n,n,y,y,y,NaN,NaN,NaN,NaN,n,y,y,y,n,y
434,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,NaN,n

In [24]:
y = preprocessing.LabelEncoder().fit_transform(df["party"].values)
df_features = df.drop(["party"], axis=1)
df_features = pd.get_dummies(df_features)
X = df_features.values

In [25]:
y_train = y[:-50]
y_test = y[-50:]
X_train = X[:-50]
X_test = X[-50:]

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
for name, clf in zip(clf_names, clfs):
    clf.fit (X_train, y_train)
    acc = accuracy_score(y_test, clf.predict(X_test))
    print ("Accuracy of %s according to cross-validation: %s" % (name, acc))

Accuracy of k-Nearest Neighbors according to cross-validation: 0.9
Accuracy of Decision Tree according to cross-validation: 0.92
Accuracy of Random Forest according to cross-validation: 0.94
Accuracy of Neural Net according to cross-validation: 0.94
Accuracy of Naive Bayes according to cross-validation: 0.92
Accuracy of AdaBoost according to cross-validation: 0.94

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)